### ISSUE TITLE
cannot run flutter pub run squirrel:installer_windows

### ISSUE THREAD

**Issue by aditdiqdpratama** [anaisbetts/squirrel-flutter#2]
```
Unhandled exception:
NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("windows")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:63:5)
#1      new PubspecParams.fromYaml (file:///C:/Users/diqdq/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/squirrel-0.1.0/bin/installer_windows.dart:131:52)
#2      main (file:///C:/Users/diqdq/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/squirrel-0.1.0/bin/installer_windows.dart:212:33)
```

**Comment by Vasco-90** [comment]
In your pubspec.yml you have to add

```yaml
squirrel:
   windows: 
     ....
```
